# Numpy Exercise

In [8]:
import numpy as np

### Creating an array using numpy

In [9]:
fruit = np.array(["Apple", "Orange", "Cherry"])
fruit

array(['Apple', 'Orange', 'Cherry'], dtype='<U6')

In [10]:
price = np.array([5, 7, 8])
price

array([5, 7, 8])

In [11]:
type(price)

numpy.ndarray

In [12]:
type(fruit)

numpy.ndarray

In [13]:
len(fruit)

3

In [14]:
len(price)

3

#### Indexing

In [15]:
fruit[1]

'Orange'

In [16]:
fruit[0:]

array(['Apple', 'Orange', 'Cherry'], dtype='<U6')

In [17]:
price.mean()

6.666666666666667

In [19]:
price.max()

8

#### Zeros

In [21]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

#### Ones

In [23]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

#### Empty

This function create arbitrary values

In [24]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [26]:
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

#### Range

In [27]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Specify

In [30]:
np.arange(2, 18)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

#### Specific Interval

In [31]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Table 

In [33]:
np.arange(6, 66, 6)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [34]:
np.arange(7, 77, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

#### Specific line space

In [38]:
np.linspace(1, 10, num=7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

#### Specify data type

In [40]:
np.ones(45, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1], dtype=int64)

In [41]:
np.ones(45, dtype=np.float32)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

# Array Functions

In [43]:
a = np.array([10, 23, 16, 17, 3.4, 56, 189, 200])
a

array([ 10. ,  23. ,  16. ,  17. ,   3.4,  56. , 189. , 200. ])

In [45]:
a.sort()
a

array([  3.4,  10. ,  16. ,  17. ,  23. ,  56. , 189. , 200. ])